version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "daily"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
